import React from 'react';
import {View, Button, ScrollView} from 'react-native';
import RazorpayCheckout from 'react-native-razorpay';

const PaymentScreen = () => {
  const handlePayment = () => {
    fetch('http://192.168.0.153:3000/api/payments/create-order', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        amount: 500, // Amount in INR
      }),
    })
      .then(response => response.json())
      .then(order => {
        console.log('This is a new order details :::', order);
        const options = {
          description: 'Payment for Order',
          image: 'https://your-logo-url.com',
          currency: order.currency,
          key: 'rzp_test_8vfxL0YRtZ6sZJ', // Replace with your key id
          amount: order.amount,
          order_id: order.id, // Add order_id generated by Razorpay
          prefill: {
            email: 'customer.email@example.com',
            contact: '9876543210',
            name: 'Customer Name',
          },
          theme: {color: '#53a20e'},
        };

        RazorpayCheckout.open(options)
          .then(data => {
            // Handle success
            console.log(`Success: ${data.razorpay_payment_id}`);

            // Verify the payment on the server
            fetch('http://192.168.0.153:3000/api/payments/verify-payment', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                order_id: order.id,
                payment_id: data.razorpay_payment_id,
                signature: data.razorpay_signature,
              }),
            })
              .then(response => response.json())
              .then(result => {
                if (result.status === 'success') {
                  alert('Payment successful!');
                } else {
                  alert('Payment verification failed.');
                }
              });
          })
          .catch(error => {
            // Handle failure
            console.log(`Error: ${error.code} | ${error.description}`);
          });
      })
      .catch(error => {
        console.error(error);
      });
  };

  return (
    <ScrollView>
      <View
        style={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
          height: 500,
        }}>
        <Button title="Pay Now" onPress={handlePayment} />
      </View>
    </ScrollView>
  );
};

export default PaymentScreen;
